spring:
  cloud:
    consul:
      discovery:
        ip-address: localhost
        port: 8500
        hostname: consul-miya
        service-name: consul-miya
  application:
    name: consul-miya
server:
  port: 8502

