eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: configSer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/li3055/project
          search-paths: respo
          username:
          password:
          default-label: master